# Generated by Django 5.0.6 on 2024-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinicio', '0002_auto_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imgauto',
            field=models.ImageField(blank=True, null=True, upload_to='imgauto'),
        ),
    ]
