# Generated by Django 5.0.6 on 2024-07-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
